export const setMessages = (id, messages) => ({ type: 'SET_MESSAGES', id, messages })
export const clearMessages = (id) => ({ type: 'CLEAR_MESSAGES', id })
export const nextStage = ({ nextStageId: stage }) => ({ type: 'LDAP_ADD_STAGE', stage })
export const prevStage = () => ({ type: 'LDAP_REMOVE_STAGE' })
export const setOptions = (options) => ({type: 'SET_OPTIONS', options})
export const editConfig = (id, value) => ({ type: 'EDIT_CONFIG', id, value })
export const editConfigs = (values) => ({ type: 'EDIT_CONFIGS', values })
export const setDefaults = (values) => ({ type: 'SET_DEFAULTS', values })
export const clearWizard = () => ({ type: 'CLEAR_WIZARD' })
export const start = (id) => ({ type: 'fetch/START', id })
export const end = (id) => ({ type: 'fetch/END', id })
